config/routes.rb
Rails.application.routes.draw do
  get 'about/index'

  get 'about/education'

  get 'about/portfolio'

  get 'about/hire'

  get 'about/contact'

  get 'welcome/index'

 root to: 'welcome#index'
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end

  def education
  end

  def portfolio
  end

  def hire
  end

  def contact
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/about/contact.html.erb
<h1>About#contact</h1>
<p>Find me in app/views/about/contact.html.erb</p>

app/views/about/education.html.erb
<h2 id= 'about-title'><b>Educational Background</b></h2>

<div class="col-md-10 col-md-offset-1">
  <h3 id= 'edu-title'>Bloc.io</h3>
  <h4 id= 'edu-sec'><q>Ruby on Rails Apprentice</q></h4>
  <div class="jumbotron">
  </div>
</div>
<div class="col-md-10 col-md-offset-1">
  <h3 id= 'edu-title'>Virginia Commonwealth University</h3>
  <h4 id= 'edu-sec'><q>B.S. Economics & Business</q></h4>
  <div class="jumbotron">
  </div><hr>
</div>

<p id='edu-btn'>
  <%= link_to "Continue", about_portfolio_path, class: 'btn btn-info' %>
</p>

app/views/about/hire.html.erb
  <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
  <script src="//code.jquery.com/jquery-1.10.2.js"></script>
  <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>


<h2 id= 'about-title'>Resume</h2>
<div id="accordion">
  <h3>Section 1</h3>
  <div>
    <p>
   Andar en bicicleta.
    </p>
  </div>
  <h3>Section 2</h3>
  <div>
    <p>
    Sed non urna. Donec et ante. Phasellus eu ligula. Vestibulum sit amet
    purus. Vivamus hendrerit, dolor at aliquet laoreet, mauris turpis porttitor
    velit, faucibus interdum tellus libero ac justo. Vivamus non quam. In
    suscipit faucibus urna.
    </p>
  </div>
  <h3>Section 3</h3>
  <div>
    <p>
    Nam enim risus, molestie et, porta ac, aliquam ac, risus. Quisque lobortis.
    Phasellus pellentesque purus in massa. Aenean in pede. Phasellus ac libero
    ac tellus pellentesque semper. Sed ac felis. Sed commodo, magna quis
    lacinia ornare, quam ante aliquam nisi, eu iaculis leo purus venenatis dui.
    </p>
    <ul>
      <li>List item one</li>
      <li>List item two</li>
      <li>List item three</li>
    </ul>
  </div>
  <h3>Section 4</h3>
  <div>
    <p>
    Cras dictum. Pellentesque habitant morbi tristique senectus et netus
    et malesuada fames ac turpis egestas. Vestibulum ante ipsum primis in
    faucibus orci luctus et ultrices posuere cubilia Curae; Aenean lacinia
    mauris vel est.
    </p>
    <p>
    Suspendisse eu nisl. Nullam ut libero. Integer dignissim consequat lectus.
    Class aptent taciti sociosqu ad litora torquent per conubia nostra, per
    inceptos himenaeos.
    </p>
  </div>
</div><br><hr>
<p id='edu-btn'>
  <%= link_to "continue", about_contact_path, class: 'btn btn-info' %>
</p>

 <script>
  $(function() {
    $( "#accordion" ).accordion();
  });
  </script>


  

app/views/about/index.html.erb
<h2 id= 'about-title'> Who is Chris Lee?</h2> 
<div class= 'row'>
  <div class= 'col-md-6'>
    <h3 id='sub-t'>heading 1</h3>
    <div class= 'jumbotron'>
      <ul>
        <li>Hello</li>
        <li></li>
      </ul>
    </div>
  </div>
  <div class= 'col-md-6'>
    <h3 id='sub-t'>Heading 2</h3>
    <div class= 'jumbotron'>
      <ul>
        <li>Hello</li>
        <li></li>
      </ul>
    </div>
  </div>
</div>
<div class= 'row'>
  <div class= 'col-md-6'>
    <h3 id='sub-t'>heading 3</h3>
    <div class= 'jumbotron'>
      <ul>
        <li>Hello</li>
        <li></li>
      </ul>
    </div>
  </div>
  <div class= 'col-md-6'>
    <h3 id= 'sub-t'>heading 4</h3>
    <div class= 'jumbotron'>
      <ul>
        <li>Hello</li>
        <li></li>
      </ul>
    </div>
  </div>
</div><hr>
<div>
  <p id= 'edu-btn'>
    <%= link_to "Continue", about_education_path, class: 'btn btn-info' %>
  </p>
</div>

app/views/about/portfolio.html.erb
<h2 id= 'about-title'>Recent Work</h2>
<div class='row'>
  <div class= 'col-md-4'>
     <h5>Want to track your fitness success, and need help in the process?</h5>
      <a class='btn btn-success'>Yes</a>
      <a class='btn btn-danger'>Not Really</a>
    <div class='jumbotron'>
     
     
      <ul id= "no-show">
        <li>Track Results!</li>
        <li>Track Progress!</li>
      </ul>
    </div>
  </div>
  <div class= 'col-md-4'>
    <div class='jumbotron'>
      <h5>Maybe you want to contribute your thoughts to a given topic?</h5>
    </div>
  </div>
  <div class= 'col-md-4'>
    <div class='jumbotron'>
      <h5>Have you created an application and want to track events?</h5>
    </div>
  </div>
</div>

<p id='edu-btn'>
  <%= link_to "continue", about_hire_path, class: 'btn btn-info' %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Journey</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
   <ul>
      <ul class= "nav nav-tabs">
        <li><%= link_to "Home", welcome_index_path %></li>
        
   </ul>
   
<%= yield %>
  
  </div>

</body>
</html>

app/views/welcome/index.html.erb
<div class = 'jumbotron'>
  <h1 id= 'intro-title'>Get To Know</h1>
  <h1 id= 'intro-name'> Chris Lee </h1>
  <h3 id= 'intro-desc'><q>An aspiring Junior Ruby on Rails Developer</q></h3>
    <p id= 'btn'>
      <%= link_to "My Story", about_index_path,class: 'btn btn-success' %>
    </p>
</div>
<h4 id="dis"><b>Disclaimer:</b> At anytime you may exit this story, however you would be missing out on the possibility of adding a passionate young developer to the RTS Labs culture! Chris is a passionate young developer that is seeking the opportunity to grow in a culture that promotes a hard working, collaborative, and drama free environment. If this sounds like a guy you want on your team, then I encourage you to proceed forward.</h4> 